on:
  schedule:
    - cron: '01 12 * * *'

jobs:
  url_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://daphnes.fly.dev/
